config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks"}

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    # TODO: Change routes to something simple like "home" instead of "home#index"
    # Change links (paths) accordingly: i.e. - home_songs_path => songs_path

    get 'home/index'
    get 'home/songs' => 'home#songs'
    root to: 'home#index'

    # http://blog.takady.net/blog/2015/11/29/rails-routing-with-username-instead-of-id/
    # resources :users, param: :name, path: '/' do
    resources :users do
      resources :songs do
        member do
          get :print
          post :print
        end
      end

      resources :set_lists do
        resources :set_list_songs do
          member do
            patch :move
          end
        end
      end

      # Songs should be like on their respective page,
      # but it ultimately belongs to the user and
      # they can remove it
      resources :favorites, only: [:create, :destroy]
    end

  end
end

app/models/set_list.rb
class SetList < ApplicationRecord
  belongs_to :user
  has_many :set_list_songs, -> { order(position: :asc) }, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3, maximum: 25 }

  # It may be a better practice to add limit: 10 to this,
  # but since the set list songs are being saved in their own controller,
  # the create function handles the logic there.
  accepts_nested_attributes_for :set_list_songs
end

app/controllers/set_lists_controller.rb
class SetListsController < ApplicationController
  before_action :get_user
  before_action :set_set_list, only: [:show, :edit, :update, :destroy]
  before_action :set_song, only: [:index]

  # GET /set_lists
  # GET /set_lists.json
  def index
    @set_lists = @user.set_lists
  end

  # GET /set_lists/1
  # GET /set_lists/1.json
  def show
  end

  # GET /set_lists/new
  def new
    @set_list = @user.set_lists.build
  end

  # GET /set_lists/1/edit
  def edit
  end

  # POST /set_lists
  # POST /set_lists.json
  def create
    @set_list = @user.set_lists.build(set_list_params)

    respond_to do |format|
      if @set_list.save
        format.html { redirect_to user_path(@user), notice: t(:set_list_created) }
        format.json { render :show, status: :created, location: @set_list }
      else
        format.html { render :new }
        format.json { render json: @set_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /set_lists/1
  # PATCH/PUT /set_lists/1.json
  def update
    respond_to do |format|
      if @set_list.update(set_list_params)
        format.html { redirect_to user_set_list_path(@user, @set_list), notice: t(:set_list_updated) }
        format.json { render :show, status: :ok, location: @set_list }
      else
        format.html { render :edit }
        format.json { render json: @set_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /set_lists/1
  # DELETE /set_lists/1.json
  def destroy
    @set_list.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@user), notice: t(:set_list_deleted) }
      format.json { head :no_content }
    end
  end

  private

  def get_user
    @user = User.find(params[:user_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_set_list
    @set_list = SetList.find(params[:id])
  end

  def set_song
    @song = params[:song_id] ? Song.find(params[:song_id]) : nil
  end

  # Only allow a list of trusted parameters through.
  def set_list_params
    params.require(:set_list).permit(:title, :user_id)
  end
end

app/views/set_lists/_form.html.erb
<%= form_for([@user, set_list]) do |form| %>
  <% if set_list.errors.any? %>
    <%= render partial: "shared/error_partial", locals: { model_instance: @set_list } %>
  <% end %>

  <div class="field text-center">
    <strong><%= t(:set_list_title) %></strong><br />
    <%= form.text_field :title, style: 'font-size: 20px; text-decoration: none;' %>
  </div>

  <p class="text-center">
    <%= t(:set_list_explanation).html_safe %>
  </p>

  <div class="set_list_songs text-center">
    <% if !set_list.set_list_songs.empty? %>
      <div data-controller="drag" data-drag-url="set_list_songs/:id/move">
        <% set_list.set_list_songs.each do |sls| %>
          <% song = Song.find(sls.song_id) %>
          <div data-id="<%= sls.id %>" class="card card-body mb-4">
            <%= link_to edit_user_set_list_set_list_song_path(@user, set_list, sls) do %>
              <%= song.title + '(' + sls.key + ')' %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="set_list_links text-center">
    <%= form.submit class: 'btn btn-primary', value: t(:save) %>
    <%# TODO: only show this if the set list actually exists %>
    <%# difference between new and show actions %>
    <%#= link_to t(:show), user_set_list_path(@user, @set_list), class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/set_lists/_select.html.erb
<div class="text-center">
  <% if current_user.set_lists.empty? %>
    <p><%= t(:you_have_no_set_lists).html_safe %></p>
  <% else %>
      <p>「<%= @song.title %>」を好きなセットリストに追加してください。</p>
      <p> 歌はこのキーで追加されます：<%= params[:selected_key] %></p>

      <% @set_lists.each do |sl| %>
        <% @set_list_song = sl.set_list_songs.build %>
        <%= form_for([current_user, sl, @set_list_song]) do |f| %>
          <%= f.hidden_field :set_list_id, value: sl.id %>
          <%= f.hidden_field :song_id, value: @song.id %>
          <%= f.hidden_field :key, value: params[:selected_key] %>
          <br />

          <%= button_tag sl.title, type: 'submit', class: 'btn btn-primary' %>
        <% end %>
      <% end %>
  <% end %>
</div>

app/views/set_lists/edit.html.erb
<h1><%= t(:edit_set_list) %></h1>

<hr>

<%= render 'form', set_list: @set_list %>

app/views/set_lists/index.html.erb
<h1><%= t(:set_lists) %></h1>

<% if params[:song_id] != nil %>
    <%= render 'select', song_id: params[:song_id] %>
<% else %>
  <div class="text-center">
    <table style="margin-left: auto; margin-right: auto;">
      <thead>
        <tr>
          <th><%= t(:set_list_title) %></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @set_lists.each do |set_list| %>
          <tr>
            <td><%= link_to set_list.title, user_set_list_path(@user, set_list) %></td>
            <td><%= link_to t(:edit), edit_user_set_list_path(@user, set_list) %></td>
            <td><%= link_to t(:delete), user_set_list_path(@user, set_list), method: :delete, data: { confirm: t(:confirm_deletion) } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br />

    <%= link_to '<i class="fa fa-pencil"></i> '.html_safe + t(:new_set_list),
      new_user_set_list_path(@user),
      class: 'btn btn-primary btn-sm',
      id: 'new_set_list_button'
    %>
  </div>
<% end %>

app/views/set_lists/new.html.erb
<h1><%= t(:new_set_list) %></h1>

<%= render 'form', set_list: @set_list %>

app/views/set_lists/show.html.erb
<%= javascript_pack_tag 'initialize_song' %>

<div id="set_list_title" class="text-center">
  <%= @set_list.title %>
</div>

<% @set_list.set_list_songs.each do |sls| %>
  <% @song = Song.find(sls.song_id) %>

  <div>
    <div class="text-center">
      <h2 id="song_title"><%= @song.title %></h2>
    </div>

    <div class="song_key">
      <%= t('activerecord.attributes.song.key') + ": " + sls.key %><br />
    </div>

    <div class="song_body set_list_song" value="<%= @song.key + "/" + sls.key %>"><%= sanitize @song.song_body %></div>
    <br />
  </div>
<% end %>

<div class="set_list_links text-center">
  <% if current_user == @user %>
    <%= link_to t(:edit), edit_user_set_list_path(@user, @set_list), class: 'btn btn-secondary' %>
      <%= link_to t(:delete), user_set_list_path(current_user, @set_list), method: :delete, data: { confirm: t(:confirm_deletion) }, class: 'btn btn-danger' %>
    <br />
  <% end %>

  <strong><%= t(:set_list_made_by) %></strong>
  <%= link_to user_path(@user) do %>
    <%= image_tag get_user_image, class: 'user_thumbnail' %>
    <%= @user.username %>
  <% end %>
</div>

<%= javascript_pack_tag 'key_change' %>