config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks"}

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    # TODO: Change routes to something simple like "home" instead of "home#index"
    # Change links (paths) accordingly: i.e. - home_songs_path => songs_path

    get 'home/index'
    get 'home/songs' => 'home#songs'
    root to: 'home#index'

    # http://blog.takady.net/blog/2015/11/29/rails-routing-with-username-instead-of-id/
    # resources :users, param: :name, path: '/' do
    resources :users do
      resources :songs do
        member do
          get :print
          post :print
        end
      end

      resources :set_lists do
        resources :set_list_songs do
          member do
            patch :move
          end
        end
      end

      # Songs should be like on their respective page,
      # but it ultimately belongs to the user and
      # they can remove it
      resources :favorites, only: [:create, :destroy]
    end

  end
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  attr_accessor :login

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :confirmable, :lockable, :timeoutable,
         :omniauthable, omniauth_providers: [:facebook, :twitter, :google_oauth2],
         :authentication_keys => [:login]

  has_many :songs, dependent: :destroy
  has_many :set_lists, dependent: :destroy
  has_many :set_list_songs, through: :set_lists, dependent: :destroy
  has_many :favorites, through: :songs, dependent: :destroy
  accepts_nested_attributes_for :favorites

  # TODO: Use carrierwave to edit user images
  # mount_uploader :user_image, UserImageUploader

  # TODO: Test multiple blank email users,
  # We allow blank here because oauth doesn't save the user's email to the database.
  validates :email, presence: true, email: true, unless: :omniauth_user?
  validates :username, presence: true, length: { minimum: 5, maximum: 30 }, unless: :omniauth_user?
  validates :password, presence: true, length: { minimum: 6, maximum: 30 }, unless: :omniauth_user?, if: :password_required?

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth["provider"], uid: auth["uid"]) do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]

      # The sub logic for the images helps display the size you choose
      # TODO: Add a thumbnail column to the users and save small pictures to that attribute
      if auth["provider"] == "twitter"
        user.username = auth["info"]["nickname"]
        user.user_image = auth["info"]["image"].sub("_normal", "")
      elsif auth["provider"] == "facebook"
        user.username = auth["info"]["name"]
        user.user_image = auth["info"]["image"] + "&type=large"
      elsif auth["provider"] == "google_oauth2"
        user.username = auth["info"]["name"]
        user.user_image = auth["info"]["image"].sub(/=s\d+/, "=s300")
      end
    end
  end

  def omniauth_user?
    self.provider.present?
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
      end
    else
      super
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(condition).first
    end
  end

  # Since :validatable has been removed, we don't need password validation when
  # updating the user's information on user#edit view. This method allows us to skip the validation.
  def password_required?
    !persisted? || !password.nil? || !password_confirmation.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @users = User.page(params[:page]).per(25)
  end

  def show
    @user = User.friendly.find(params[:id])
    @songs = @user.songs.page(params[:page]).per(25)
  end

  def edit
    @user = User.friendly.find(params[:id])
  end

  def update
    @user = User.friendly.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to (@user), notice: t(:user_updated) }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.friendly.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: t(:user_deleted) }
      format.json { head :no_content }
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_image, :username)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def get_user_image
    # TODO: Check Facebook Developer's settings and see what can be done to fix this
    if @user.user_image.present? && !!@user.user_image.match(/^http:/)
      user_image = @user.user_image.gsub(/^http/, "https")
    else
      user_image = @user.user_image
    end

    @user.user_image ? user_image : 'user_black_logo.jpg'
  end
end

app/views/users/_charts.html.erb
<div id="charts_header" class="text-center">
  <% if current_user == @user %>
    <%= link_to '<i class="fa fa-pencil"></i> '.html_safe + t(:new_chart),
      new_user_song_path(@user),
      class: 'btn btn-primary btn-sm',
      id: 'new_chart_button'
    %>
  <% end %>

  <p><%= @user.username + t(:user_charts) %></p>
</div>

<div class="charts">
  <% if !@songs.empty? %>
    <div>
      <span style="margin-left: 5px"><%= t('activerecord.attributes.song.title') %></span>
      <span class="pull-right" style="margin-right: 5px;"><%= t('activerecord.attributes.song.key') %></span>
    </div>

    <ul class="list-group">
      <% @songs.each do |song| %>
        <% user = User.find(song.user_id) %>
        <%= link_to user_song_path(@user, song), id: 'user_songs', class: 'list-group-item' do %>
          <span><%= song.title%></span>

          <span class="pull-right">
            <%= song.key %>
          </span>
        <% end %>
      <% end %>
    </ul>
  <% else %>
    <div class="card card-body text-center">
      <h4><%= t(:no_charts) %></h4>
    </div>
  <% end %>

  <!--div class="song_pagination text-center"-->
    <%#= paginate @songs %>
  <!--/div-->
</div>

app/views/users/_favorites.html.erb
<div class="favorites_header">
  <p class="text-center">
    <%= @user.username + t(:honorific) + t(:possessive) + t(:favorited_songs) %>
  </p>
</div>

<div class="favorites">
  <% if !@user.favorites.empty? %>
    <div>
      <span style="margin-left: 5px"><%= t('activerecord.attributes.song.title') %></span>
      <span class="pull-right" style="margin-right: 5px;"><%= t(:chart_made_by) %></span>
    </div>

    <ul class="list-group">
      <% @user.favorites.each do |favorite| %>
        <% song = Song.find(favorite.song_id) %>
        <% song_user = User.find(song.user_id) %>

        <%= link_to user_song_path(@user, song), class: 'list-group-item' do %>
          <span><%= song.title %></span>
          <span class="pull-right">
            <%= image_tag song_user.user_image, class: 'user_thumbnail user_image_thumbnail' %>
            <%= song_user.username %>
          </span>
        <% end %>
      <% end %>
    </ul>
  <% else %>
    <h4 class="text-center"><%= t(:no_favorites) %></h4>
  <% end %>
</div>

app/views/users/_profile.html.erb
<div class="row">
  <div class="col-xs-2 hidden-md"></div>

  <div class="card col-xs-8 col-md-12">
    <div class="card-body text-center">
      <%= button_tag class: 'btn btn-link', data: {toggle: "modal", target: '#img_modal'} do %>
        <%= image_tag(image_url(get_user_image), id: 'user_image', alt: 'user image') %>
      <% end %>

      <div class="modal fade" id="img_modal" tabindex="-1" role="dialog" aria-labelledby="img_modal_label" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="btn btn-secondary pull-right" data-dismiss="modal">×</button>
            </div>
            <div class="modal-body">
              <%= image_tag(image_url(get_user_image), id: 'modal_user_image', width: '400', height: '400') %>
            </div>
          </div>
        </div>
      </div>

      <h2><%= @user.username %></h2>

      <% if current_user == @user %>
        <hr>
        <%= link_to t(:edit_profile), edit_user_path(@user) %><br />
        <%= link_to t(:delete_account), user_path, method: :delete, data: { confirm: t(:confirm_deletion) } %>
      <% end %>
    </div>
  </div>

  <div class="col-xs-2 hidden-md"></div>
</div>

app/views/users/_set_lists.html.erb
<div class="new_set_list_button_div text-center">
  <% if current_user == @user %>
    <!-- TODO: Same CSS as new_chart_button -->
    <%= link_to '<i class="fa fa-pencil"></i> '.html_safe + t(:new_set_list),
      new_user_set_list_path(@user),
      class: 'btn btn-primary btn-sm',
      id: 'new_set_list_button'
    %>
  <% end %>
</div>

<div class="set_lists_header text-center">
  <p><%= @user.username + t(:honorific) + t(:possessive) + t(:set_lists) %></p>
</div>

<div class="set_lists">
  <% if !@user.set_lists.empty? %>
    <ul class="list-group">
      <% @user.set_lists.each do |sl| %>
        <%= link_to sl.title, user_set_list_path(@user, sl), class: 'list-group-item text-center' %><br />
      <% end %>
    </ul>
  <% else %>
    <h4 class="text-center"><%= t(:no_set_lists) %></h4>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="text-center">
  <p><%= t(:edit_picture) %></p>

  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="image_error" class="card">
        <div class="card-body">
          <h2><%= pluralize(@user.errors.count, t(:errors_occurred)) %></h2>
        </div>

        <% @user.errors.full_messages.each do |message| %>
          <p class="alert alert-danger image_error_details"><%= message %></p>
        <% end %>
      </div>
    <% end %>

    <div class="form-group">
      <% if @user.user_image? %>
        <div class="thumbnail">
          <%= image_tag get_user_image %>
        </div>
      <% end %>
      <%#= f.file_field :user_image %>
      <%#
          Had this hidden field when I was using carrierwave.
          I might still use it so the user can edit their image,
          so I don't think I'll delete it for now.
      %>
      <%# f.hidden_field :user_image_cache %>
    </div>

    <%= f.text_field :username %><br />

    <%= f.submit class: 'btn btn-primary', value: t(:save), id: 'save_button' %>
  <% end %>
</div>

app/views/users/index.html.erb
<% if @users != nil %>
  <div id="users_index" class="container-fluid">
    <h1><%= t(:list_of_users) %></h1>

    <div class="row">
      <div class="col-xs-0 col-lg-4"></div>

      <ul class="list-group col-xs-12 col-lg-4">
        <% @users.each do |user| %>
          <li class="list-group-item"><%# TODO: if user.confirmed? の人だけにするかな %>
            <% if user.user_image == nil %>
              <%# Hard code height and width for default pic because it's not using carrierwave to resize %>
              <%= image_tag('user_black_logo.jpg', class: 'user_image_thumbnail', height: '50', width: '50') %>
            <% else %>
              <%= image_tag(user.user_image, class: 'user_thumbnail', style: 'height: 60px;') %>
            <% end %>

            <%= link_to(user.username, user_path(user)) %>
            <% if current_user && current_user.admin %>
              <%= link_to t(:delete), user_path(user), method: :delete, data: { confirm: t(:confirm_deletion) } %>
            <% end %>
          </li>
        <% end %>
      </ul>

      <div class="col-xs-0 col-lg-4"></div>
    </div>

    <div class="row">
      <div class="col-xs-0 col-lg-4"></div>

      <div class="pagination col-xs-12 col-lg-4 text-center">
        <%= paginate @users %>
      </div>

      <div class="col-xs-0 col-lg-4"></div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div id="user_container" class="container">
  <div id="user_row" class="row">

    <div id="user_info" class="col-xs-12 col-md-4">
      <%= render 'profile' %>
    </div>

    <div id="user_data" class="col-xs-12 col-md-8">
      <%= render 'charts' %>

      <%= render 'favorites' %>

      <%= render 'set_lists' %>
    </div>
  </div>
</div>