config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks"}

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    # TODO: Change routes to something simple like "home" instead of "home#index"
    # Change links (paths) accordingly: i.e. - home_songs_path => songs_path

    get 'home/index'
    get 'home/songs' => 'home#songs'
    root to: 'home#index'

    # http://blog.takady.net/blog/2015/11/29/rails-routing-with-username-instead-of-id/
    # resources :users, param: :name, path: '/' do
    resources :users do
      resources :songs do
        member do
          get :print
          post :print
        end
      end

      resources :set_lists do
        resources :set_list_songs do
          member do
            patch :move
          end
        end
      end

      # Songs should be like on their respective page,
      # but it ultimately belongs to the user and
      # they can remove it
      resources :favorites, only: [:create, :destroy]
    end

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def songs
    @songs = Song.page(params[:page]).search(params[:search]).per(25)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_chart_results.html.erb
<%# TODO: Display artist on right side like user/show.html.erb's songs panel %>

<% @results.each do |song| %>
	<% user = User.find(song.user_id) %>
	<%= link_to song.title, user_song_path(user, song) %>
<% end %>

app/views/home/_user_results.html.erb
<%# TODO: user/index.html.erbとほぼ同じ形式がからrefactorした方がいいかもしれない %>

<ul class="list-group col-xs-12 col-lg-4">
    <% @results.each do |user| %>
        <li class="list-group-item"><%# TODO: if user.confirmed? の人だけにするかな %>
            <% if user.user_image.file == nil %>
             	<%# Hard code height and width for default pic because it's not using carrierwave to resize %>
            	<%= image_tag('user_black_logo.jpg', id: 'user_image_thumbnail', height: '50', width: '50') %>
            <% else %>
            	<%= image_tag(user.user_image.url(:thumb).to_s, id: 'user_image_thumbnail') %>
            <% end %>

            <%= link_to(user.name, user_path(user)) %>
            <% if current_user && current_user.admin %>
            	<%= link_to t(:delete), user_path(user), method: :delete, data: { confirm: t(:confirm_deletion) } %>
            <% end %>
        </li>
    <% end %>
</ul>

app/views/home/index.html.erb
<%= javascript_pack_tag 'initialize_song' %>

<header id="sanbikaHeader" class="masthead">
  <div class="container">
    <div class="jumbotron" id="home_jumbotron" style="color: black;">
      <h1><%= t(:welcome) %></h1><br />
      <p>
        <%= t(:psalm150_6) %>
        <i class="text-muted"><%= t(:psalm150_6_ref) %></i>
      </p>
      <br />
      <%= link_to t(:list_of_charts), home_songs_path, class: 'btn btn-primary'%>
      <%= link_to t(:list_of_users), users_path, class: 'btn btn-primary' %>
    </div>
  </div>
</header>

<div class="container">
    <div id="homepage_login_links">
        <div class="row">

            <div class="col-xs-0 col-md-3"></div>

            <div class="jumbotron_inner col-xs-12 col-md-6">
              <%= render 'devise/shared/links_short_version' %>
            </div>

            <div class="col-xs-0 col-md-3"></div>
        </div>
    </div>
</div>

<div id="features_header">
  <div class="row">
    <div class="feature col-xl-12 col-lg-4">
      <div class="feature_text_wrapper">
        <span class="feature_text"><%= t(:simple_keychange) %></span>
      </div>
      <div class="feature_wrapper">
        <i class="fa fa-music"></i>
      </div>
    </div>
    <div class="feature col-xl-12 col-lg-4">
      <div class="feature_text_wrapper">
        <span class="feature_text"><%= t(:simple_creation) %></span>
      </div>
      <div class="feature_wrapper">
        <i class="fa fa-pencil"></i>
      </div>
    </div>
    <div class="feature col-xl-12 col-lg-4">
      <div class="feature_text_wrapper">
        <span class="feature_text"><%= t(:post_videos) %></span>
      </div>
      <div class="feature_wrapper">
        <i class="fa fa-film"></i>
      </div>
    </div>
  </div>
</div>

<div id="example_chart" class="container-fluid">
  <div class="example_banner_text_wrapper text-center">
    <h1 id="example_banner_text"><%= t(:try_it_out) %></h1>
  </div>
  <div class="panel panel-default">
    <div class="panel panel-heading">
      <h1 class="song_title"><%= t(:example_chart_title) %></h1>
      <div class="text-center">
        <%= t('activerecord.attributes.song.key') %>
        <%= select_tag(
            :key_box,
            options_for_select(sharp_notes, selected: t(:example_chart_key)),
            class: t(:example_chart_key))
        %>
      </div>
    </div>
    <div class="song_body" class="panel panel-body"><%= t(:example_chart) %></div>
  </div>
</div>

<footer id="main_footer" class="text-right">
  <%= link_to '<i class="fa fa-twitter"></i>'.html_safe, 'https://www.twitter.com/sanbika_jp' , target: '_blank' %>
  <%= link_to '<i class="fa fa-github"></i>'.html_safe, 'https://www.github.com/gazayas/sanbika' , target: '_blank' %>
</footer>

<%= javascript_pack_tag 'key_change' %>

<script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
<script>
  window.sr = ScrollReveal();
  sr.reveal('.feature_wrapper');
</script>

app/views/home/search.html.erb
<div class="row text-center">
	<div class="panel panel-default">
		<div class="panel panel-body">
			<div class="col-xs-12 col-md-6 text-left">
				<div class="col-xs-2 hidden-md"></div>

				<%= form_tag '/search', method: :post, class: 'col-xs-8' do |f| %>
					<p>
						<%= t(:search_for_a_chart) %>
						<% 4.times do %>
							&nbsp;
						<% end %>
						<%= select_tag :search_filter, options_for_select([t(:artist), t(:title), t(:lyrics)]) %>
					</p>
					<%= text_field_tag :search_contents %>

					<%= submit_tag t(:search), class: 'btn btn-primary' %>
				<% end %>

				<div class="col-xs-2 hidden-md"></div>
			</div>

			<div class="col-xs-12 col-md-6 text-left">
				<div class="col-xs-2 hidden-md"></div>

				<%= form_tag '/search', method: :post, class: 'col-xs-8' do |f| %>
					<p><%= t(:search_for_a_user) %></p>
					<%= hidden_field_tag :search_filter, "User" %>
					<%= text_field_tag :search_contents %>

					<%= submit_tag t(:search), class: 'btn btn-primary' %>
				<% end %>

				<div class="col-xs-2 hidden-md"></div>
			</div>
			<div class="col-xs-2 hidden-md"></div>
		</div>
	</div>
</div>

<div class="panel panel-default" id="songs_index">
	<div class="panel panel-heading">
  	  <h1>Results</h1>
  	</div>
  	<div class="panel panel-body">
		<ul class="list-group">
	  		<% if @results.empty? %>
	  			<p>No results</p>
		  	<% else %>
				<% if params[:search_filter] == "Title" || params[:search_filter] == "Artist" %>
					<%= render 'chart_results' %>
				<% else %>
					<%= render 'user_results' %>
				<% end %>
		    <% end %>
		  </ul>
	</div>
</div>

<div class="pagination_container">
  <%= paginate @results unless @results.empty? %>
</div>

app/views/home/songs.html.erb
<div class="container-fluid">
  <% if @songs  %>
    <div class="panel panel-default" id="songs_index">
      <div class="panel panel-heading">
        <h1><%= t(:list_of_charts) %></h1>
      </div>
      <ul class="list-group">
        <% @songs.each do |song| %>
          <% user = User.find(song[:user_id]) %>
          <li class="list-group-item"><%= link_to(song.title, user_song_path(user, song)) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="pagination_container">
    <%= paginate @songs if @songs %>
  </div>
</div>