config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks"}

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    # TODO: Change routes to something simple like "home" instead of "home#index"
    # Change links (paths) accordingly: i.e. - home_songs_path => songs_path

    get 'home/index'
    get 'home/songs' => 'home#songs'
    root to: 'home#index'

    # http://blog.takady.net/blog/2015/11/29/rails-routing-with-username-instead-of-id/
    # resources :users, param: :name, path: '/' do
    resources :users do
      resources :songs do
        member do
          get :print
          post :print
        end
      end

      resources :set_lists do
        resources :set_list_songs do
          member do
            patch :move
          end
        end
      end

      # Songs should be like on their respective page,
      # but it ultimately belongs to the user and
      # they can remove it
      resources :favorites, only: [:create, :destroy]
    end

  end
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :user
	has_many :set_list_songs, dependent: :destroy
	has_many :favorites, dependent: :destroy

	VIDEO_REGEXP = /\A(http)?(s)?(:\/\/)?(www\.youtube\.com\/watch\?(time_continue=\d+\&)?(v=))|(youtu\.be\/)(.*)\z/

	validates :title, presence: true, length: { maximum: 50 }, uniqueness: { scope: :user_id }
	validates :key, presence: true, length: { maximum: 2 }
	validates :song_body, presence: true, length: { maximum: 7_000_000 }
	validates :video, :check_link, length: { maximum: 300 }

	# TODO: Change the Regular Expression so it matches with upcase/downcase
	# Returns all instances if there are no search hits.
	def self.search(search)
		if search
			where(['title LIKE ?', "%#{search}%"])
    else
			all
		end
	end

	private

	# TODO: There is also "format" in Rails validations.
	# Check and see if that is a better option
	def check_link
		errors.add(:video, I18n.t(:invalid_link)) unless video == "" || !!video.match(VIDEO_REGEXP)
	end

	def self.favorites
		Favorite.where(song_id: self.id)
	end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :print]

  def show
    @user = User.find(@song.user_id)

    if @song.video && !@song.video.empty?
      @video_id = @song.video.gsub(/(.*)(watch\?v=)/, "")
    end

    @favorite = current_user_favorite
  end

  def new
    @user = User.friendly.find(params[:user_id])
    @song = @user.songs.build
  end

  def edit
    @song = Song.find(params[:id])
    @user = User.find(@song[:user_id])
  end

  def create
    @user = User.friendly.find(params[:user_id])
    @song = @user.songs.build(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to ([@user, @song]), notice: t(:song_created) }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(@song[:user_id])

    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to ([@user, @song]), notice: t(:song_updated) }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(@song[:user_id])
    @song.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@user), notice: t(:song_deleted) }
      format.json { head :no_content }
    end
  end

  def print
    @user = User.friendly.find(params[:user_id])
    @song = Song.find(params[:id])

    is_pdf = false

    respond_to do |format|
      format.html
      format.pdf do
        is_pdf = true
        html = render_to_string template: "songs/print"
        pdf = PDFKit.new(html, encoding: "UTF-8")

        send_data pdf.to_pdf,
          filename: "#{@song.id}.pdf",
          type: "application/pdf",
          disposition: "inline"
      end
    end

    if !is_pdf
      render layout: 'print'
    end
  end

  private

  def set_song
      @song = Song.find(params[:id])
  end

  def current_user_favorite
      current_user ? current_user.favorites.find_by_song_id(@song.id) : nil
  end

  def song_params
      params.require(:song).permit(:title, :key, :song_body, :video)
  end
end

app/helpers/songs_helper.rb
module SongsHelper
  def sharp_notes
    ["A", "A♯", "B", "C", "C♯", "D", "D♯", "E", "F", "F♯", "G", "G♯"]
  end
end

app/views/songs/_form.html.erb
<% col_size = 50 %>

<%= form_for([@user, song]) do |f| %>
  <% unless song.key == nil %>
    <% key = song.key %>
  <% else %>
    <% key = "C" %>
  <% end %>

  <table class="song_form" style="margin: 0px auto;">
    <tr>
      <td>
        <%= f.text_field :title, class: 'form-control',
        placeholder: t('activerecord.attributes.song.title'), autofocus: true, size: col_size %>
      </td>
    </tr>
    <tr>
      <td>
         <div class="text-center">
             <%= t('activerecord.attributes.song.key') %>
             <%= f.select(:key, options_for_select(sharp_notes, selected: key),
             class: 'form-control', size: col_size) %>
         </div>
      </td>
    </tr>
  </table>

  <div class="song_form explanation">
    <%= t(:explanation) %><br />
  </div>

  <div class="song_form song_body">
    <%= f.text_area :song_body, class: 'song_form_song_body' %>
  </div>

  <table class="song_form">
    <tr>
      <td>
        <%= t(:link_to_youtube) %>
        <%= f.text_field :video, class: 'form-control',
        placeholder: t('activerecord.attributes.song.video'), size: col_size %>
      </td>
    </tr>
  </table>

  <div class="text-center">
    <%= f.submit class: 'btn btn-primary', value: t(:save), id: 'save_button' %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<!-- 変数名をmodel_instanceとして定義し、部分テンプレートで使う -->
<%= render partial: "shared/error_partial", locals: { model_instance: @song } %>


<h3 class="text-center"><%= t(:edit_chart) %></h3>
</div>
  <%= render 'form', song: @song %>
</div>

<div class="text-center">
	<%= link_to t(:show), user_song_path(@user, @song) %>
</div>

app/views/songs/new.html.erb
<!-- エラーの部分はedit.html.erbの方とかぶっているのでpartialを書いた方がいいかもしれない -->
<%= render partial: "shared/error_partial", locals: { model_instance: @song } %>

<div class="card-body">
    <h1><%= t(:new_chart) %></h1>
</div>

<%= render 'form', song: @song %>

app/views/songs/print.pdf.erb
<!-- TODO: 選択されたキーをここに渡してkey_changeを行う事 -->
<div class="panel panel-default">
  <div class="panel panel-heading">
    <%= content_tag(:h2, @song.title, id: 'song_title') %>
  </div>
</div>

<div id="song_body">
  <%= simple_format(@song.song_body) %>
</div>

app/views/songs/show.html.erb
<%= javascript_pack_tag 'initialize_song' %>

<div class="show_container">
    <div class="song_title text-center">
      <%= @song.title %>
      <% if current_user %>
        <span id="favorite">
          <%= render 'shared/favorite', song: @song %>
        </span>
      <% end %>
    </div>

    <div class="container text-center">
      <% form_path = current_user ? user_set_lists_path(current_user) : user_song_path(@user, @song) %>
      <%= form_tag(form_path, method: "GET") do %>
        <%= hidden_field_tag :song_id, @song.id %>
          <strong><%= t('activerecord.attributes.song.key') %></strong>
          <%= select_tag(
                :selected_key,
                options_for_select(sharp_notes, selected: @song.key),
                id: 'key_box',
                class: @song.key)
          %>
        <%= submit_tag('Add to Set List', class: 'btn btn-primary') if current_user %>
      <% end %>

      <strong>
        <%= t(:hide_chords) %>
        <%= check_box_tag "hide chords", nil, false, class: 'visibility_checkbox', style: 'display: inline-block;' %>
      </strong>

      <div class="song_body"><%= sanitize(@song.song_body) %></div>
    </div>

    <% if @video_id %>
      <div id="song_video_container">
        <div class="embed-responsive embed-responsive-16by9">
          <iframe
            width="560"
            height="315"
            src="https://www.youtube.com/embed/<%= @video_id %>"
            frameborder="0"
            allowfullscreen>
          </iframe>
        </div>
      </div>
    <% end %>

    <%# link_to t(:print), print_user_song_path, class: 'hidden-xs' %>
    <div class="text-center">
      <%= form_for(@song, url: {action: 'print'}, method: 'POST') do |f|%>
        <%= f.hidden_field :selectedKey, value: @song.key %>
        <%= f.submit t(:print), class: 'btn btn-secondary', id: 'print_button' %>
      <% end %>

      <%# link_to 'pdf', print_user_song_path(format: "pdf") %>

      <div style="margin: 10px;">
        <strong><%= t(:chart_made_by) %></strong>
        <br />
        <%= image_tag(get_user_image, id: 'user_image_thumbnail', class: 'user_thumbnail') %>
        <%= link_to @user.username, @user %>
      </div>

      <br />

      <% if current_user && (@user == current_user || current_user.admin) %>
        <%= link_to t(:edit), edit_user_song_path(@user, @song), class: 'btn btn-secondary' %>
        <%= link_to t(:back), user_path(@user), class: 'btn btn-secondary' %>
        <%= link_to t(:delete), user_song_path, class: 'btn btn-danger', method: :delete, data: { confirm: t(:confirm_deletion) } %>
      <% end %>
      </div>
</div>

<%= javascript_pack_tag 'key_change' %>